#Hands on #1


## Estrutura da aula
1. Google Colab
  - Overview
  - Cópia do aluno

2. Python 3
  - String
  - 


## Google Colab

## Python 3

### Manipulação de string e I/O de string

Como solicitar informações de input para o usuário em forma de string?

Como inserir variáveis string formatadas de uma maneira flexível?

In [ ]:
# Ask user for name

name = input("What is your name?: ")

# Ask user for age

age = input("How old are you?: ")

# Ask user for city

city = input("What city do you live in?: ")

# Ask user what they enjoy

love = input("What do you love doing?: ")

# Create output text

string = "Your name is {} and you are {} years old. You live in {} and you love {}"
output = string.format(name, age, city, love)

# Print output to screen
print(output)

## Numpy

In [ ]:
import numpy as np

# Criação de um array
arr = np.array([1,2,6,7],dtype='uint8')  
print(arr,'\n')

# Funções interessantes
dimensoes = (3,3)
zeros = np.zeros(dimensoes, dtype='uint8')
print(zeros,'\n')

uns = np.ones(dimensoes, dtype='uint8')
print(uns,'\n')

vazio = np.empty(dimensoes, dtype='uint8')
print(vazio,'\n')

[1 2 6 7] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 



In [ ]:
# Operações Básicas

# Soma
arr = arr + 10 
#arr = arr + np.array([])
print("Sum is:\n",arr)
# Subtração
arr = arr - 10 
#arr = arr + np.array([])
print("Subtraction is:\n",arr)
# Multiplicação
arr = arr*2 
print("Multiplication is:\n",arr)
# Divisão
arr = arr/2
print("Division is:\n",arr)

Sum is:
 [11. 12. 16. 17.]
Subtraction is:
 [1. 2. 6. 7.]
Multiplication is:
 [ 2.  4. 12. 14.]
Division is:
 [1. 2. 6. 7.]


In [ ]:
# Numpy Array vs Numpy Matrix

array1 = np.array([[1,2],[4,5]], dtype='uint8')
print("Array is:\n", array1)
id = [[1,0],[0,1]]

print("Matrix multiplication\n Array is:\n",array1@id)
print("Multiplcation of arrays\n Array is:\n",array1*id)

matriz = np.matrix([[8,9],[3,4]], dtype='uint8')
matriz = matriz+10

print("Matrix is:\n", matriz)
print("Matrix multiplicationq\nMatrix is:\n", matriz@id)
print("Array  multiplication\nMatrix is:\n", matriz*id)


Array ar is:
 [[1 2]
 [4 5]]
Matrix multiplication
 Array is:
 [[1 2]
 [4 5]]
Multiplcation of arrays
 Array is:
 [[1 0]
 [0 5]]
Matrix is:
 [[18 19]
 [13 14]]
Matrix multiplicationq
Matrix is:
 [[18 19]
 [13 14]]
Array  multiplication
Matrix is:
 [[18 19]
 [13 14]]


In [ ]:
# Acesso à informação de Array

# Shape
print(np.shape(vetor))

# Slicing
#parte = arr[inicio:fim:passo,inicio:fim:passo]

# Data type
arr = arr.astype('float64') 
print(arr.dtype)
arr = arr.astype('uint8') 
print(arr.dtype)

vazio = np.empty(dimensoes, dtype='float')
print(vazio,'\n')



(4,)
float64
uint8
[[2.9210141e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]] 



## Opencv

In [ ]:
import cv2 as cv
from google.colab.patches import cv2_imshow

# imread
image = cv.imread(url)
image = cv.imread(DriveDir)

# Imshow
cv2_imshow(image_2)

# formato das imagens(bmp,jpg, png,...)

# Color Mapping(Gray, RGB, BGR)
image = cv.cvtColor(image , cv.COLOR_BGR2RGB)
image = cv.cvtColor(image , cv.COLOR_BGR2GRAY)

# Resize
resized = cv2.resize(img, (outputDim1,outputDim2), interpolation=cv2.INTER_LINEAR)

# Imsave
 cv2.imwrite('/path/to/destination/image.png',image)